<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [2]:
1x = int(input("Enter no of rows Matrix1:"))
y = int(input("Enter no of columns Matrix1:"))
w = int(input("Enter no of rows Matrix2:"))
z = int(input("Enter no of columns Matrix2:"))

if y != w:
  print("This matrix multiplication cannot be done")
else:

 A = [[int(input()) for i in range(y)] for q in range(x)]
 print("Matrix 1:")
 for i in range(x):
   for j in range(y):
    print(format(A[i][j], "<3"), end=" ")
   print()

 B = [[int(input()) for i in range(z)] for q in range(y)]
 print("Matrix 1:")
 for i in range(y):
   for j in range(z):
     print(format(B[i][j], "<3"), end=" ")
   print()



 r = [[0 for i in range(z)] for j in range(y)]
 
 print("Matrix :")
 for i in range(x):
   for j in range(z):
     for k in range(y):
       r[i][j] += A[i][k] * B[k][j]


 print("result :")
 for i in range(x):
   for j in range(y):
     print(format(r[i][j], "<3"), end=" ")
   print()



Enter no of rows Matrix1:3
Enter no of columns Matrix1:3
Enter no of rows Matrix2:3
Enter no of columns Matrix2:3
1
3
4
2
5
7
5
9
6
Matrix 1:
1   3   4   
2   5   7   
5   9   6   
1
0
0
0
1
0
0
0
1
Matrix 1:
1   0   0   
0   1   0   
0   0   1   
Matrix :
result :
1   3   4   
2   5   7   
5   9   6   


<h3> Q2: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [1]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# try to complete this question using regular expressions
# you can free to change all these codes/structure
# String: it will be the input to your program
# https://www.w3schools.com/python/python_regex.asp

def replace_digits(String):
    r=re.sub("[^1-9]", "", String)
    s=re.sub("[^A-z]", "#", r )
    print(s) 


A = input()
replace_digits(A)


#2a$#b%c%561# 
####


<h3> Q3: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
#run your code in the function for each of the inputs mentioned above and make sure that you get the same results

# you can free to change all these codes/structure
def curve_smoothing(string):
    
    return #list of values



In [ ]:
S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(# print above values)

<h3> Q4: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
import re
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
# a,b,c = string_features(S1, S2)
# print(#the above values)
S1_words = set(re.split("\s",S1))
S2_words = set(re.split("\s",S2))
X = S1_words & S2_words
y = S1_words- S2_words
Z = S2_words- set(X)

print(len(X))
print(list(y))
print(list(Z))


7
['5', 'first', 'F']
['S', 'second', '3']
